// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXSpTvFWtbsrz8YxOnKhBzJON-dWE86_I',
    appId: '1:494091059615:web:e499b8c5d416f8cae1fdaa',
    messagingSenderId: '494091059615',
    projectId: 'friendly-spaces',
    authDomain: 'friendly-spaces.firebaseapp.com',
    storageBucket: 'friendly-spaces.appspot.com',
    measurementId: 'G-5DP6S8ZV0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaUV5BK4bknfv6XZh03aKHQTqwJhi2_8I',
    appId: '1:494091059615:android:ae67ca2b0a8b78afe1fdaa',
    messagingSenderId: '494091059615',
    projectId: 'friendly-spaces',
    storageBucket: 'friendly-spaces.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6CgowUf06NC9ZjAr0N2hE8wB77fgUwCQ',
    appId: '1:494091059615:ios:27ed5192ead3eb00e1fdaa',
    messagingSenderId: '494091059615',
    projectId: 'friendly-spaces',
    storageBucket: 'friendly-spaces.appspot.com',
    iosBundleId: 'com.example.friendlySpaces',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6CgowUf06NC9ZjAr0N2hE8wB77fgUwCQ',
    appId: '1:494091059615:ios:07f4df9e06ebc629e1fdaa',
    messagingSenderId: '494091059615',
    projectId: 'friendly-spaces',
    storageBucket: 'friendly-spaces.appspot.com',
    iosBundleId: 'com.example.friendlySpaces.RunnerTests',
  );
}
